/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package djorapp;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class Parkirmasuk extends javax.swing.JFrame {

String nomor_transaksi, plat, tanggal,jamMulai, menitMulai, jeniskendaraan, lokasiParkir;

    public Parkirmasuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTNoPolisi = new javax.swing.JTextField();
        TXTLokasiParkir = new javax.swing.JTextField();
        BTNSimpan = new javax.swing.JButton();
        BTNReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTNoTransaksi = new javax.swing.JTextField();
        jenKendaraan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jam_park = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        menit_park = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tanggal_park = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA PARKIR");

        jLabel2.setText("No. Plat:");

        jLabel3.setText("Jenis Kendaraan:");

        jLabel4.setText("Lokasi Parkir:");

        TXTNoPolisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNoPolisiActionPerformed(evt);
            }
        });
        TXTNoPolisi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNoPolisiKeyTyped(evt);
            }
        });

        TXTLokasiParkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTLokasiParkirActionPerformed(evt);
            }
        });
        TXTLokasiParkir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTLokasiParkirKeyTyped(evt);
            }
        });

        BTNSimpan.setText("Simpan");
        BTNSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSimpanActionPerformed(evt);
            }
        });

        BTNReset.setText("Reset");
        BTNReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNResetActionPerformed(evt);
            }
        });

        jLabel9.setText("No. Parkir:");

        jenKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenKendaraanActionPerformed(evt);
            }
        });
        jenKendaraan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jenKendaraanKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Jika motor, masukkan angka 1. Jika mobil, masukkan angka 2.");

        jLabel11.setText("Jam:");

        jam_park.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam_parkActionPerformed(evt);
            }
        });
        jam_park.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jam_parkKeyTyped(evt);
            }
        });

        jLabel12.setText(":");

        menit_park.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menit_parkActionPerformed(evt);
            }
        });
        menit_park.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                menit_parkKeyTyped(evt);
            }
        });

        jLabel13.setText("Tanggal:");

        tanggal_park.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_parkActionPerformed(evt);
            }
        });
        tanggal_park.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tanggal_parkKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXTNoPolisi)
                                .addComponent(TXTNoTransaksi)
                                .addComponent(TXTLokasiParkir)
                                .addComponent(jenKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jam_park, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(menit_park, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tanggal_park, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BTNSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNReset)
                        .addGap(129, 129, 129))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(71, 71, 71))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(TXTNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(TXTNoPolisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jenKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTLokasiParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal_park, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jam_park, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(menit_park, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNSimpan)
                    .addComponent(BTNReset))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggal_parkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tanggal_parkKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_parkKeyTyped

    private void tanggal_parkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_parkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_parkActionPerformed

    private void menit_parkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menit_parkKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_menit_parkKeyTyped

    private void menit_parkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menit_parkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menit_parkActionPerformed

    private void jam_parkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jam_parkKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jam_parkKeyTyped

    private void jam_parkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam_parkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jam_parkActionPerformed

    private void jenKendaraanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jenKendaraanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jenKendaraanKeyTyped

    private void jenKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenKendaraanActionPerformed

    private void BTNResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNResetActionPerformed
        // TODO add your handling code here:
        TXTNoTransaksi.setText("");
        TXTNoPolisi.setText("");
        TXTLokasiParkir.setText("");
        tanggal_park.setText("");
        jam_park.setText("");
        menit_park.setText("");
        jenKendaraan.setText("");

    }//GEN-LAST:event_BTNResetActionPerformed

    private void BTNSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSimpanActionPerformed
        try {
            Class.forName("org.mariadb.jdbc.Driver").newInstance();
            String url = "jdbc:mariadb://localhost/parkingsys?user=root&password=lusiana0507";
            Connection connection = DriverManager.getConnection(url);

            nomor_transaksi = TXTNoTransaksi.getText();
            plat =  TXTNoPolisi.getText();
            tanggal= tanggal_park.getText();
            jamMulai = jam_park.getText();
            menitMulai = menit_park.getText();
            lokasiParkir = TXTLokasiParkir.getText();
            jeniskendaraan = jenKendaraan.getText();

            String sql = "Select * from lokasi_parkir where nomor_slot = '"+lokasiParkir+"' and status = 1 ";
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();

            if(rs.next() == true){
                String Input = "insert into transaksi (nomor_transaksi, tglParkir, jam_mulai, menit_mulai, jeniskendaraan, nomorslot) values ('"+nomor_transaksi+"', '"+tanggal+"', '"+jamMulai+"', '"+menitMulai+"','"+jeniskendaraan+"', '"+lokasiParkir+"' )";
                statement = connection.prepareStatement(Input);
                rs = statement.executeQuery();
                JOptionPane.showMessageDialog(null, "Data Pemarkir berhasil disimpan." + "\n" + "Nomor Parkir: " + nomor_transaksi);

                String ubahTanda = "update lokasi_parkir set status = false where nomor_slot = '"+lokasiParkir+"' and status = 1";
                statement = connection.prepareStatement(ubahTanda);
                rs = statement.executeQuery();

                new pendataan().setVisible(true);        // TODO add your handling code here:
                setDefaultCloseOperation(Parkirmasuk.DISPOSE_ON_CLOSE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Data Pemarkir gagal disimpan.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BTNSimpanActionPerformed

    private void TXTLokasiParkirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTLokasiParkirKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_TXTLokasiParkirKeyTyped

    private void TXTLokasiParkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTLokasiParkirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTLokasiParkirActionPerformed

    private void TXTNoPolisiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNoPolisiKeyTyped
        // TODO add your handling code here:
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_TXTNoPolisiKeyTyped

    private void TXTNoPolisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNoPolisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNoPolisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parkirmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parkirmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parkirmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parkirmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parkirmasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNReset;
    private javax.swing.JButton BTNSimpan;
    private javax.swing.JTextField TXTLokasiParkir;
    private javax.swing.JTextField TXTNoPolisi;
    private javax.swing.JTextField TXTNoTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jam_park;
    private javax.swing.JTextField jenKendaraan;
    private javax.swing.JTextField menit_park;
    private javax.swing.JTextField tanggal_park;
    // End of variables declaration//GEN-END:variables
}
