/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package djorapp;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author wiranda.siahaan
 */
public class Pembayaran extends javax.swing.JFrame {


    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
  
        initComponents();
        label_found.setText("");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nosearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        label_found = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Biaya Parkir");

        jLabel2.setText("No.Parkir");

        Nosearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NosearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kendaraan  :");

        jLabel4.setText("No. Slot  :");

        jLabel5.setText("Tgl Parkir  :");

        jLabel6.setText("Durasi Jam  :");

        jLabel7.setText("Durasi Hari :");

        jLabel8.setText("Lama Parkir  :");

        jLabel9.setText("Biaya Parkir   :");

        btnCetak.setText("Cetak Struk");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        label_found.setText("Not Found !");

        jLabel10.setText("No.Parkir");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(label_found))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel14))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel16))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(125, 125, 125)
                                    .addComponent(jLabel11))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel17))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(33, 33, 33)
                                    .addComponent(Nosearch, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(searchButton))))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nosearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_found)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NosearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NosearchActionPerformed
        // TODO add your handling code here:
            Nosearch.setText("");
    }//GEN-LAST:event_NosearchActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if (Nosearch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data masing kosong!");
        } else {
            PrintJob p = getToolkit().getPrintJob(this, "Cetak Tiket", null);

            Graphics g = p.getGraphics();
            g.setFont(new Font("Serif", Font.BOLD, 20));
            g.drawString("TIKET NO: "+Nosearch.getText(), 200, 18);
            g.drawLine(10, 30, 600, 30);
            g.setFont(new Font("Courier New", Font.PLAIN, 12));
            g.drawString("No. Parkir", 10, 50);
            g.drawString(" : ", 100, 50);
            g.drawString(Nosearch.getText(), 160, 50);

            g.drawString("Jenis", 10, 60);
            g.drawString(" : ", 100, 60);
            g.drawString(jLabel11.getText(), 160, 60);

            g.drawString("No Slot", 10, 70);
            g.drawString(" : ", 100, 70);
            g.drawString(jLabel12.getText(), 160, 70);

            g.drawString("Tanggal Parkir", 10, 80);
            g.drawString(" : ", 100, 80);
            g.drawString(jLabel13.getText(), 160, 80);

            g.drawString("Waktu Mulai", 10, 90);
            g.drawString(" : ", 100, 90);
            g.drawString(jLabel14.getText(), 160, 90);

            g.drawString("Waktu Selesai", 10, 100);
            g.drawString(" : ", 100, 100);
            g.drawString(jLabel15.getText(), 160, 100);

            g.drawString("Lama Parkir", 10, 110);
            g.drawString(" : ", 100, 110);
            g.drawString(jLabel16.getText(), 160, 110);

            g.drawString("Biaya Parkir", 10, 120);
            g.drawString(" : ", 100, 120);
            g.drawString(jLabel17.getText(), 160, 120);

            g.setFont(new Font("Courier New", Font.PLAIN, 8));
            g.drawString("*Parkiran Yang Dikenakan Biaya Parkir, Hanya Kendaraan dengan lama parkir Lebih dari 1 Jam", 10, 150);
            g.drawString("*Parkir lebih dari 1 Jam dikenai biaya Rp 20.000,00 persatu Jam nya", 10, 160);

            p.end();
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:

        if ("".equals(Nosearch.getText())) {
            label_found.setText(" Silahkan masukkan No Parkir Terlebih Dulu");
            this.info_Jenis_Kendaraan.setText("Jenis_Kendaraan : ");                 
            this.info_No_Slot.setText("No_Slot : ");
            this.info_Waktu_Mulai.setText("Waktu_Mulai : ");
            this.info_Waktu_Selesai.setText("Waktu_Selesai : ");
            this.info_Lama_Parkir.setText("Lama_Parkir : ");
            this.info_tgl_Parkir.setText("tgl_Parkir: ");
            this.info_Biaya_Parkir.setText("Biaya_Parkir: ")
                    
        } else {
            
            a.connect("localhost", "mariadb", "root", "123456789");

            //disini

            Parkir No = a.getinfoNoParkiran(Nosearch.getText());

            if (No  == null && p == null ) {
                label_found.setText("");
                this.No_Parkir.setText("No_Parkir :" + No.getNo_Parkir() + "  not found!");
                this.info_Jenis_Kendaraan.setText("Jenis_Kendaraan : ");                 
                this.info_No_Slot.setText("No_Slot : ");
                this.info_Waktu_Mulai.setText("Waktu_Mulai : ");
                this.info_Waktu_Selesai.setText("Waktu_Selesai : ");
                this.info_Lama_Parkir.setText("Lama_Parkir : ");
                this.info_tgl_Parkir.setText("tgl_Parkir: ");
                this.info_Biaya_Parkir.setText("Biaya_Parkir: ")
                        
            } else {

                label_found.setText("");
                this.No_Parkir.setText("No_Parkir :" + No.getNo_Parkir());
                this.info_Jenis_Kendaraan.setText("Jenis_Kendaraan : "+ No.getJenis_Kendaraan());              
                this.info_No_Slot.setText("No_Slot : "+ No.getNo_Slot());   
                this.info_Waktu_Mulai.setText("Waktu_Mulai : "+ No.getWaktu_Mulai());   
                this.info_Waktu_Selesai.setText("Waktu_Selesai : "+ No.getWaktu_Selesai());   
                this.info_Lama_Parkir.setText("Lama_Parkir : "+ No.getLama_Parkir());   
                this.info_tgl_Parkir.setText("tgl_Parkir: "+ No.gettgl_Parkir());   
                this.info_Biaya_Parkir.setText("Biaya_Parkir: "+ No.getBiaya_Parkir());  
                  Nosearch.setText("");        
            }
       

        
        }

    }//GEN-LAST:event_searchButtonActionPerformed
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nosearch;
    private javax.swing.JButton btnCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_found;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables

    private class info_Jenis_Kendaraan {
        String Jenis_Kendaraan;
      
        public info_Jenis_Kendaraan(String Jenis_Kendaraan) {
        this.Jenis_Kendaraan = Jenis_Kendaraan;
        }
        public String getJenis_Kendaraan(){
        
        return Jenis_Kendaraan;
    }
    
        public  void setJenis_Kendaraan(String Jenis_Kendaraan){
        this.Jenis_Kendaraan = Jenis_Kendaraan;
    }
    }

    private class info_No_Slot {
        int No_Slot;
        
        public info_No_Slot(int No_Slot) {
         this.No_Slot= No_Slot;
        }
        public int getNo_Slot(){
        
        return No_Slot;
    }
    
        public  void setNo_Slot(int No_Slot){
        this.No_Slot = No_Slot;
        }
    }

    private class info_Waktu_Mulai {
        int Waktu_Mulai;

        public info_Waktu_Mulai(int Waktu_Mulai){
            this.Waktu_Mulai = Waktu_Mulai;
        }
         public int getWaktu_Mulai(){
        
        return Waktu_Mulai;
    }
    
        public  void setWaktu_Mulai(int Waktu_Mulai){
        this.Waktu_Mulai = Waktu_Mulai;
        }
    }

    private class info_Waktu_Selesai {
        int Waktu_Selesai;
        
        public info_Waktu_Selesai(int Waktu_Selesai) {
         this.Waktu_Selesai = Waktu_Selesai;
        }
         public int getWaktu_Selesai(){
        
        return Waktu_Selesai;
    }
    
        public  void setWaktu_Selesai(int Waktu_Selesai ){
        this.Waktu_Selesai = Waktu_Selesai;
        }
    }

    private class info_Lama_Parkir {
        int Lama_Parkir;
                
        public info_Lama_Parkir(int Lama_Parkir) {
         this.Lama_Parkir = Lama_Parkir;
        }
         public int getLama_Parkir(){
        
        return Lama_Parkir;
    }
    
        public  void setLama_Parkir(int Lama_Parkir ){
        this.Lama_Parkir = Lama_Parkir;
        }
    }

    private class info_Biaya_Parkir {
        int Biaya_Parkir;
        
        public info_Biaya_Parkir() {
        this.Biaya_Parkir = Biaya_Parkir;
        }
         public int getBiaya_Parkir(){
        
        return Biaya_Parkir;
        }
    
        public  void setBiaya_Parkir(int Biaya_Parkir ){
        this.Biaya_Parkir = Biaya_Parkir;
        }
    }

    private class info_tgl_Parkir {
            date tgl_Parkir;
            
        public info_tgl_Parkir() {
         this.tgl_Parkir = tgl_Parkir;
        }
         public int getBiaya_Parkir(date tgl_Parkir){
        
        return tgl_Parkir;
        }
    
        public  void setBiaya_Parkir(date tgl_Parkir ){
        this.tgl_Parkir = tgl_Parkir;
        }
    }
    }
   

    
   

